export const US_STATES: { code: string; count: number }[] = [
  { code: "AK", count: 24 },
  { code: "AL", count: 363 },
  { code: "AR", count: 316 },
  { code: "AZ", count: 389 },
  { code: "CA", count: 3147 },
  { code: "CO", count: 387 },
  { code: "CT", count: 330 },
  { code: "DC", count: 105 },
  { code: "DE", count: 115 },
  { code: "FL", count: 2143 },
  { code: "GA", count: 910 },
  { code: "HI", count: 91 },
  { code: "IA", count: 161 },
  { code: "ID", count: 79 },
  { code: "IL", count: 1123 },
  { code: "IN", count: 443 },
  { code: "KS", count: 107 },
  { code: "KY", count: 379 },
  { code: "LA", count: 374 },
  { code: "MA", count: 678 },
  { code: "MD", count: 624 },
  { code: "ME", count: 70 },
  { code: "MI", count: 897 },
  { code: "MN", count: 476 },
  { code: "MO", count: 291 },
  { code: "MS", count: 234 },
  { code: "MT", count: 40 },
  { code: "NC", count: 858 },
  { code: "ND", count: 48 },
  { code: "NE", count: 121 },
  { code: "NH", count: 124 },
  { code: "NJ", count: 1068 },
  { code: "NM", count: 107 },
  { code: "NV", count: 178 },
  { code: "NY", count: 1906 },
  { code: "OH", count: 816 },
  { code: "OK", count: 202 },
  { code: "OR", count: 244 },
  { code: "PA", count: 1143 },
  { code: "RI", count: 111 },
  { code: "SC", count: 698 },
  { code: "SD", count: 82 },
  { code: "TN", count: 504 },
  { code: "TX", count: 2022 },
  { code: "UN", count: 2 },
  { code: "UT", count: 132 },
  { code: "VA", count: 761 },
  { code: "VT", count: 21 },
  { code: "WA", count: 478 },
  { code: "WI", count: 413 },
  { code: "WV", count: 123 },
  { code: "WY", count: 17 },
];

export const REGIONS: { id: string; label: string; count: number }[] = [
  { id: "usa", label: "USA", count: 26475 },
  { id: "america", label: "America", count: 4117 },
  { id: "europe", label: "Europe", count: 13815 },
  { id: "oceania", label: "AU.Oceania", count: 1222 },
  { id: "asia", label: "Asia", count: 3743 },
  { id: "africa", label: "Africa", count: 288 },
];

export const FLAG_EMOJI: Record<string, string> = {
  US: "🇺🇸",
  CA: "🇨🇦",
  MX: "🇲🇽",
  BR: "🇧🇷",
  AR: "🇦🇷",
  CL: "🇨🇱",
  CO: "🇨🇴",
  GB: "🇬🇧",
  DE: "🇩🇪",
  FR: "🇫🇷",
  NL: "🇳🇱",
  ES: "🇪🇸",
  IT: "🇮🇹",
  PL: "🇵🇱",
  SE: "🇸🇪",
  NO: "🇳🇴",
  AU: "🇦🇺",
  NZ: "🇳🇿",
  JP: "🇯🇵",
  KR: "🇰🇷",
  SG: "🇸🇬",
  IN: "🇮🇳",
  CN: "🇨🇳",
  HK: "🇭🇰",
  ZA: "🇿🇦",
  NG: "🇳🇬",
  EG: "🇪🇬",
  KE: "🇰🇪",
};
